from __future__ import annotations

import json
import os
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import timedelta
from pathlib import Path
from typing import Any, Protocol

import httpx

from errors import ErrorCode, ServiceError
from models import (
    DiscoverTokensRequest,
    InspectMarketRequest,
    InspectTokenRequest,
    InspectWalletRequest,
    ProviderName,
    ReviewSignalsRequest,
)
from ot_skill_enterprise.shared.contracts.common import utc_now


DEFAULT_VENDOR_SCRIPT = (
    Path(__file__).resolve().parents[2] / "vendor" / "ave_cloud_skill" / "scripts" / "ave_data_rest.py"
)


class ProviderAdapter(Protocol):
    name: ProviderName

    def discover_tokens(self, payload: DiscoverTokensRequest) -> dict[str, Any]: ...

    def inspect_token(self, payload: InspectTokenRequest) -> dict[str, Any]: ...

    def inspect_market(self, payload: InspectMarketRequest) -> dict[str, Any]: ...

    def inspect_wallet(self, payload: InspectWalletRequest) -> dict[str, Any]: ...

    def review_signals(self, payload: ReviewSignalsRequest) -> dict[str, Any]: ...


@dataclass(slots=True)
class MockProvider:
    name: ProviderName = ProviderName.MOCK

    def discover_tokens(self, payload: DiscoverTokensRequest) -> dict[str, Any]:
        base = (payload.query or payload.source or "ave").strip()
        symbol = base.upper()[:6] or "AVE"
        chain = payload.chain or "unknown"
        now = utc_now()
        return {
            "token_refs": [
                {
                    "identifier": f"{chain}:{symbol}",
                    "chain": chain,
                    "token_address": f"0x{symbol.lower():0<40}"[:42],
                    "symbol": symbol,
                    "name": f"{base.title()} Token",
                    "rank": 1,
                    "score": 92.0,
                    "source": payload.source or "mock",
                },
                {
                    "identifier": f"{chain}:{symbol}X",
                    "chain": chain,
                    "token_address": f"0x{(symbol + 'x').lower():0<40}"[:42],
                    "symbol": f"{symbol[:4]}X",
                    "name": f"{base.title()} Labs",
                    "rank": 2,
                    "score": 84.0,
                    "source": payload.source or "mock",
                },
            ][: payload.limit],
            "ranking_context": {
                "title": "Token discovery",
                "window": "24h",
                "source": payload.source or "mock",
                "note": "Generated by mock provider",
                "metadata": {"query": payload.query or "", "chain": chain},
            },
            "source_meta": {
                "provider": self.name,
                "request_id": payload.query or None,
                "fetched_at": now,
                "cached": False,
                "source_version": "mock-v1",
                "metadata": {"mode": "in-memory"},
            },
        }

    def inspect_token(self, payload: InspectTokenRequest) -> dict[str, Any]:
        token_ref = payload.token_ref
        symbol = token_ref.symbol or token_ref.identifier.upper()
        chain = token_ref.chain or "unknown"
        now = utc_now()
        return {
            "identity": {
                "identifier": token_ref.identifier,
                "chain": chain,
                "token_address": token_ref.token_address,
                "symbol": symbol,
                "name": f"{symbol} Protocol",
                "source": "mock",
            },
            "market_snapshot": {
                "price_usd": 1.2345,
                "market_cap_usd": 123_450_000,
                "fdv_usd": 234_500_000,
                "liquidity_usd": 8_750_000,
                "volume_24h_usd": 18_400_000,
                "status": "available",
            },
            "risk_snapshot": {
                "risk_level": "medium",
                "flags": ["mock-provider"],
                "honeypot": False,
                "buy_tax_bps": 0,
                "sell_tax_bps": 0,
                "status": "available",
            },
            "holder_snapshot": {
                "holder_count": 1280,
                "top_holder_share_pct": 27.0,
                "holders": [
                    {
                        "holder_address": "0x1111111111111111111111111111111111111111",
                        "quantity": 1500000,
                        "value_usd": 1850000,
                        "share_pct": 14.2,
                        "label": "mock-top-holder",
                    }
                ]
                if payload.include_holders
                else [],
                "status": "available" if payload.include_holders else "unavailable",
                "note": None if payload.include_holders else "holder data disabled by request",
            },
            "main_pair_ref": {
                "identifier": f"{symbol}/USDT",
                "chain": chain,
                "pair_address": "0xpair000000000000000000000000000000000001",
                "dex": "mockswap",
                "base_token_ref": {
                    "identifier": token_ref.identifier,
                    "chain": chain,
                    "token_address": token_ref.token_address,
                    "symbol": symbol,
                    "name": f"{symbol} Protocol",
                    "source": "mock",
                },
                "quote_token_ref": {
                    "identifier": f"{chain}:USDT",
                    "chain": chain,
                    "symbol": "USDT",
                    "name": "Tether USD",
                    "source": "mock",
                },
            },
            "source_meta": {
                "provider": self.name,
                "fetched_at": now,
                "cached": False,
                "source_version": "mock-v1",
            },
        }

    def inspect_market(self, payload: InspectMarketRequest) -> dict[str, Any]:
        token_ref = payload.token_ref
        symbol = token_ref.symbol or token_ref.identifier.upper()
        chain = token_ref.chain or "unknown"
        pair_identifier = payload.pair_ref.identifier if payload.pair_ref is not None else f"{symbol}/USDT"
        now = utc_now()
        points = []
        for idx in range(4):
            timestamp = now - timedelta(hours=idx)
            base = 1.0 + idx * 0.01
            points.append(
                {
                    "timestamp": timestamp,
                    "open": base,
                    "high": base + 0.02,
                    "low": max(base - 0.01, 0),
                    "close": base + 0.01,
                    "volume": 1000 + idx * 50,
                }
            )
        return {
            "selected_pair": {
                "identifier": pair_identifier,
                "chain": chain,
                "pair_address": payload.pair_ref.pair_address if payload.pair_ref is not None else "0xpair000000000000000000000000000000000002",
                "dex": "mockswap",
                "base_token_ref": {
                    "identifier": token_ref.identifier,
                    "chain": chain,
                    "token_address": token_ref.token_address,
                    "symbol": symbol,
                    "name": f"{symbol} Protocol",
                    "source": "mock",
                },
                "quote_token_ref": {
                    "identifier": f"{chain}:USDT",
                    "chain": chain,
                    "symbol": "USDT",
                    "name": "Tether USD",
                    "source": "mock",
                },
            },
            "ohlcv": list(reversed(points)),
            "recent_swaps": [
                {
                    "tx_hash": "0xmock1",
                    "timestamp": now - timedelta(minutes=5),
                    "side": "buy",
                    "token_ref": {
                        "identifier": token_ref.identifier,
                        "chain": chain,
                        "symbol": symbol,
                        "source": "mock",
                    },
                    "amount_base": 1200,
                    "amount_quote": 1450,
                    "trader": "0xtrader1",
                },
                {
                    "tx_hash": "0xmock2",
                    "timestamp": now - timedelta(minutes=1),
                    "side": "sell",
                    "token_ref": {
                        "identifier": token_ref.identifier,
                        "chain": chain,
                        "symbol": symbol,
                        "source": "mock",
                    },
                    "amount_base": 860,
                    "amount_quote": 1035,
                    "trader": "0xtrader2",
                },
            ],
            "flow_summary": {
                "buy_count": 14,
                "sell_count": 9,
                "net_flow_usd": 3400,
                "large_trade_count": 2,
                "note": f"{payload.window} window at {payload.interval} interval",
            },
            "source_meta": {
                "provider": self.name,
                "fetched_at": now,
                "cached": False,
                "source_version": "mock-v1",
            },
        }

    def inspect_wallet(self, payload: InspectWalletRequest) -> dict[str, Any]:
        chain = payload.chain or "unknown"
        now = utc_now()
        return {
            "wallet_summary": {
                "wallet_address": payload.wallet,
                "chain": chain,
                "label": "mock-wallet",
                "balance_usd": 7740,
                "token_count": 2,
                "status": "available",
            },
            "holdings": [
                {
                    "token_ref": {
                        "identifier": f"{chain}:AVE",
                        "chain": chain,
                        "symbol": "AVE",
                        "name": "Ave Token",
                        "source": "mock",
                    },
                    "quantity": 1200,
                    "value_usd": 2340,
                    "allocation_pct": 30.2,
                },
                {
                    "token_ref": {
                        "identifier": f"{chain}:USDT",
                        "chain": chain,
                        "symbol": "USDT",
                        "name": "Tether USD",
                        "source": "mock",
                    },
                    "quantity": 5400,
                    "value_usd": 5400,
                    "allocation_pct": 69.8,
                },
            ]
            if payload.include_holdings
            else [],
            "recent_activity": [
                {
                    "tx_hash": "0xwallet1",
                    "timestamp": now - timedelta(minutes=10),
                    "action": "swap",
                    "token_ref": {
                        "identifier": f"{chain}:AVE",
                        "chain": chain,
                        "symbol": "AVE",
                        "name": "Ave Token",
                        "source": "mock",
                    },
                    "amount_usd": 1800,
                    "note": "mock swap",
                },
                {
                    "tx_hash": "0xwallet2",
                    "timestamp": now - timedelta(minutes=3),
                    "action": "transfer",
                    "token_ref": {
                        "identifier": f"{chain}:USDT",
                        "chain": chain,
                        "symbol": "USDT",
                        "name": "Tether USD",
                        "source": "mock",
                    },
                    "amount_usd": 3200,
                    "note": "mock transfer",
                },
            ]
            if payload.include_activity
            else [],
            "source_meta": {
                "provider": self.name,
                "fetched_at": now,
                "cached": False,
                "source_version": "mock-v1",
            },
        }

    def review_signals(self, payload: ReviewSignalsRequest) -> dict[str, Any]:
        chain = payload.chain or "unknown"
        token_ref = payload.token_ref
        token_identifier = token_ref.identifier if token_ref is not None else f"{chain}:ALPHA"
        symbol = token_ref.symbol if token_ref is not None and token_ref.symbol else token_identifier.split(":")[-1].upper()
        now = utc_now()
        return {
            "signals": [
                {
                    "signal_id": "signal-001",
                    "title": f"{symbol} volume spike",
                    "severity": "high",
                    "chain": chain,
                    "token_ref": {
                        "identifier": token_identifier,
                        "chain": chain,
                        "symbol": symbol,
                        "source": "mock",
                    },
                    "description": "Detected accelerated buy pressure across tracked pools.",
                    "occurred_at": now - timedelta(minutes=8),
                    "source": "mock",
                },
                {
                    "signal_id": "signal-002",
                    "title": f"{symbol} wallet clustering",
                    "severity": "medium",
                    "chain": chain,
                    "token_ref": {
                        "identifier": token_identifier,
                        "chain": chain,
                        "symbol": symbol,
                        "source": "mock",
                    },
                    "description": "Linked wallet cluster accumulated into the same pair.",
                    "occurred_at": now - timedelta(minutes=2),
                    "source": "mock",
                },
            ][: payload.limit],
            "linked_token_refs": [
                {
                    "identifier": token_identifier,
                    "chain": chain,
                    "symbol": symbol,
                    "source": "mock",
                }
            ],
            "source_meta": {
                "provider": self.name,
                "fetched_at": now,
                "cached": False,
                "source_version": "mock-v1",
            },
        }


def _as_dict(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _as_list(value: Any) -> list[Any]:
    return value if isinstance(value, list) else []


def _data_section(payload: dict[str, Any]) -> Any:
    data = payload.get("data")
    return payload if data is None else data


def _section_dict(payload: dict[str, Any]) -> dict[str, Any]:
    section = _data_section(payload)
    return section if isinstance(section, dict) else payload


def _section_list(payload: dict[str, Any], *keys: str) -> list[Any]:
    section = _data_section(payload)
    if isinstance(section, dict):
        for key in keys:
            value = section.get(key)
            if isinstance(value, list):
                return value
    if isinstance(section, list):
        return section
    for key in keys:
        value = payload.get(key)
        if isinstance(value, list):
            return value
    return []


def _first_non_empty(*values: Any) -> Any:
    for value in values:
        if value is None:
            continue
        if isinstance(value, str) and not value.strip():
            continue
        return value
    return None


def _token_identifier(chain: str | None, entry: dict[str, Any]) -> str:
    return str(
        _first_non_empty(
            entry.get("identifier"),
            entry.get("token_id"),
            entry.get("token_identifier"),
            entry.get("address"),
            entry.get("token_address"),
            f"{chain}:{_first_non_empty(entry.get('symbol'), entry.get('name'), 'token')}",
        )
    )


def _token_reference(entry: dict[str, Any], *, chain: str | None = None, fallback_source: str | None = None) -> dict[str, Any]:
    entry_chain = _first_non_empty(entry.get("chain"), chain)
    identifier = _token_identifier(entry_chain, entry)
    symbol = _first_non_empty(entry.get("symbol"), entry.get("token_symbol"))
    name = _first_non_empty(entry.get("name"), entry.get("token_name"))
    token_address = _first_non_empty(entry.get("token_address"), entry.get("address"))
    if token_address is None and identifier and ":" in identifier:
        token_address = identifier.split(":", 1)[1]
    return {
        "identifier": identifier,
        "chain": entry_chain,
        "token_address": token_address,
        "symbol": symbol,
        "name": name,
        "rank": entry.get("rank"),
        "score": entry.get("score"),
        "source": _first_non_empty(entry.get("source"), fallback_source),
    }


def _pair_reference(entry: dict[str, Any], *, fallback_token: dict[str, Any], fallback_chain: str | None = None) -> dict[str, Any]:
    chain = _first_non_empty(entry.get("chain"), fallback_chain, fallback_token.get("chain"))
    identifier = _first_non_empty(entry.get("identifier"), entry.get("pair_identifier"))
    if identifier is None:
        token_symbol = _first_non_empty(fallback_token.get("symbol"), fallback_token.get("identifier"), "TOKEN")
        identifier = f"{token_symbol}/USDT"
    base_token_ref = _first_non_empty(entry.get("base_token_ref"), entry.get("base_token"), fallback_token)
    if not isinstance(base_token_ref, dict):
        base_token_ref = fallback_token
    quote_token_ref = _first_non_empty(entry.get("quote_token_ref"), entry.get("quote_token"))
    if not isinstance(quote_token_ref, dict):
        quote_token_ref = {
            "identifier": _first_non_empty(entry.get("quote_identifier"), f"{chain}:USDT" if chain else "USDT"),
            "chain": chain,
            "token_address": None,
            "symbol": "USDT",
            "name": "Tether USD",
            "source": "ave",
        }
    return {
        "identifier": identifier,
        "chain": chain,
        "pair_address": _first_non_empty(entry.get("pair_address"), entry.get("address")),
        "dex": _first_non_empty(entry.get("dex"), entry.get("amm"), entry.get("source")),
        "base_token_ref": base_token_ref,
        "quote_token_ref": quote_token_ref,
    }


def _source_meta(payload: dict[str, Any], *, command: str, provider: ProviderName, request_id: str | None = None) -> dict[str, Any]:
    section = _section_dict(payload)
    raw_meta = _as_dict(payload.get("meta"))
    raw_top_source_meta = _as_dict(payload.get("source_meta"))
    raw_source_meta = _as_dict(section.get("source_meta"))
    return {
        "provider": provider,
        "request_id": _first_non_empty(
            request_id,
            raw_source_meta.get("request_id"),
            raw_top_source_meta.get("request_id"),
            raw_meta.get("request_id"),
            payload.get("request_id"),
        ),
        "fetched_at": _first_non_empty(
            raw_source_meta.get("fetched_at"),
            raw_top_source_meta.get("fetched_at"),
            raw_meta.get("fetched_at"),
            payload.get("fetched_at"),
            utc_now(),
        ),
        "cached": bool(_first_non_empty(raw_source_meta.get("cached"), raw_top_source_meta.get("cached"), raw_meta.get("cached"), False)),
        "source_version": _first_non_empty(
            raw_source_meta.get("source_version"),
            raw_top_source_meta.get("source_version"),
            raw_meta.get("source_version"),
            f"vendored-cli:{command}",
        ),
        "metadata": {
            **_as_dict(raw_meta.get("metadata")),
            **_as_dict(raw_top_source_meta.get("metadata")),
            **_as_dict(raw_source_meta.get("metadata")),
            "command": command,
        },
    }


def _normalize_cli_payload(payload: Any) -> dict[str, Any]:
    if not isinstance(payload, dict):
        raise ServiceError(
            code=ErrorCode.PROVIDER_ERROR,
            message="AVE CLI returned a non-JSON object",
            status_code=502,
            details={"payload_type": type(payload).__name__},
        )
    return payload


def _normalize_timestamp_points(points: list[Any]) -> list[Any]:
    if not isinstance(points, list):
        return []
    normalized: list[Any] = []
    for item in points:
        if isinstance(item, dict):
            normalized.append(item)
    return normalized


@dataclass(slots=True)
class _VendoredAveCli:
    script_path: Path = DEFAULT_VENDOR_SCRIPT
    python_executable: str = sys.executable
    timeout_seconds: float = 30.0

    def run_json(self, command: str, *args: str) -> dict[str, Any]:
        if not self.script_path.exists():
            raise ServiceError(
                code=ErrorCode.PROVIDER_UNAVAILABLE,
                message="Vendored AVE data-rest script is missing",
                status_code=503,
                details={"script_path": str(self.script_path)},
            )

        env = os.environ.copy()
        env.setdefault("AVE_IN_SERVER", "true")
        env.setdefault("AVE_USE_DOCKER", "false")

        completed = subprocess.run(
            [self.python_executable, str(self.script_path), command, *args],
            capture_output=True,
            text=True,
            env=env,
            timeout=self.timeout_seconds,
        )
        if completed.returncode != 0:
            stderr = (completed.stderr or completed.stdout or "").strip()
            raise ServiceError(
                code=ErrorCode.PROVIDER_ERROR,
                message=f"AVE CLI command failed: {command}",
                status_code=502,
                details={
                    "command": command,
                    "args": list(args),
                    "returncode": completed.returncode,
                    "stderr": stderr,
                    "script_path": str(self.script_path),
                },
            )

        output = (completed.stdout or "").strip()
        if not output:
            raise ServiceError(
                code=ErrorCode.PROVIDER_ERROR,
                message="AVE CLI returned empty output",
                status_code=502,
                details={"command": command, "args": list(args), "script_path": str(self.script_path)},
            )

        try:
            return _normalize_cli_payload(json.loads(output))
        except json.JSONDecodeError as exc:
            raise ServiceError(
                code=ErrorCode.PROVIDER_ERROR,
                message="AVE CLI returned invalid JSON",
                status_code=502,
                details={"command": command, "args": list(args), "stdout": output, "script_path": str(self.script_path)},
            ) from exc


@dataclass(slots=True)
class AveRestProvider:
    script_path: Path = DEFAULT_VENDOR_SCRIPT
    python_executable: str = sys.executable
    timeout_seconds: float = 10.0
    name: ProviderName = ProviderName.AVE_REST
    _cli: _VendoredAveCli = field(init=False, repr=False)

    def __post_init__(self) -> None:
        self._cli = _VendoredAveCli(
            script_path=self.script_path,
            python_executable=self.python_executable,
            timeout_seconds=self.timeout_seconds,
        )

    def _search(self, payload: DiscoverTokensRequest) -> dict[str, Any]:
        keyword = (payload.query or payload.source or payload.chain or "ave").strip()
        args = ["--keyword", keyword, "--limit", str(payload.limit)]
        if payload.chain:
            args.extend(["--chain", payload.chain])
        return self._cli.run_json("search", *args)

    def discover_tokens(self, payload: DiscoverTokensRequest) -> dict[str, Any]:
        raw = self._search(payload)
        section = _section_dict(raw)
        items = _section_list(raw, "token_refs", "items", "tokens", "results")
        token_refs = [_token_reference(_as_dict(item), chain=payload.chain, fallback_source=payload.source or "ave") for item in items]
        if not token_refs and isinstance(section, dict):
            token_refs = [_token_reference(section, chain=payload.chain, fallback_source=payload.source or "ave")]
        ranking_context = _as_dict(section.get("ranking_context"))
        if not ranking_context:
            ranking_context = {
                "title": _first_non_empty(section.get("title"), "Token discovery"),
                "window": _first_non_empty(section.get("window"), "24h"),
                "source": _first_non_empty(section.get("source"), payload.source, "ave"),
                "note": _first_non_empty(section.get("note"), "Vendored AVE CLI search result"),
                "metadata": {
                    "query": payload.query or "",
                    "chain": payload.chain or "",
                },
            }
        return {
            "token_refs": token_refs[: payload.limit],
            "ranking_context": ranking_context,
            "source_meta": _source_meta(raw, command="search", provider=self.name),
        }

    def _resolve_token_address(self, payload: DiscoverTokensRequest | InspectTokenRequest | InspectMarketRequest) -> str:
        token_ref = payload.token_ref
        if token_ref.token_address:
            return token_ref.token_address
        identifier = token_ref.identifier
        if ":" in identifier:
            return identifier.split(":", 1)[1]
        if "-" in identifier:
            return identifier.rsplit("-", 1)[0]
        return identifier

    def _resolve_chain(self, token_ref: Any) -> str:
        chain = getattr(token_ref, "chain", None)
        if chain:
            return chain
        identifier = getattr(token_ref, "identifier", "")
        if ":" in identifier:
            return identifier.split(":", 1)[0]
        if "-" in identifier:
            return identifier.rsplit("-", 1)[-1]
        return "unknown"

    def inspect_token(self, payload: InspectTokenRequest) -> dict[str, Any]:
        token_address = self._resolve_token_address(payload)
        chain = self._resolve_chain(payload.token_ref)
        token_raw = self._cli.run_json("token", "--address", token_address, "--chain", chain)
        token_data = _section_dict(token_raw)
        risk_raw = (
            self._cli.run_json("risk", "--address", token_address, "--chain", chain)
            if payload.include_risk
            else {}
        )
        holders_raw = (
            self._cli.run_json("holders", "--address", token_address, "--chain", chain)
            if payload.include_holders
            else {}
        )
        identity = _token_reference(
            {
                **token_data,
                "identifier": _first_non_empty(token_data.get("identifier"), payload.token_ref.identifier),
                "chain": _first_non_empty(token_data.get("chain"), chain),
                "token_address": _first_non_empty(token_data.get("token_address"), token_address),
                "symbol": _first_non_empty(token_data.get("symbol"), payload.token_ref.symbol),
                "name": _first_non_empty(token_data.get("name"), payload.token_ref.name),
                "source": _first_non_empty(token_data.get("source"), "ave"),
            },
            chain=chain,
            fallback_source="ave",
        )
        market_snapshot = {
            "price_usd": _first_non_empty(token_data.get("price_usd"), token_data.get("price")),
            "market_cap_usd": _first_non_empty(token_data.get("market_cap_usd"), token_data.get("market_cap")),
            "fdv_usd": _first_non_empty(token_data.get("fdv_usd"), token_data.get("fdv")),
            "liquidity_usd": _first_non_empty(token_data.get("liquidity_usd"), token_data.get("liquidity")),
            "volume_24h_usd": _first_non_empty(token_data.get("volume_24h_usd"), token_data.get("volume_24h")),
            "status": "available",
            "note": _first_non_empty(token_data.get("market_note"), None),
        }
        risk_data = _section_dict(risk_raw)
        risk_snapshot = {
            "risk_level": _first_non_empty(risk_data.get("risk_level"), token_data.get("risk_level")),
            "flags": _as_list(_first_non_empty(risk_data.get("flags"), token_data.get("flags"), [])),
            "honeypot": _first_non_empty(risk_data.get("honeypot"), token_data.get("honeypot")),
            "buy_tax_bps": _first_non_empty(risk_data.get("buy_tax_bps"), risk_data.get("buy_tax"), token_data.get("buy_tax_bps")),
            "sell_tax_bps": _first_non_empty(risk_data.get("sell_tax_bps"), risk_data.get("sell_tax"), token_data.get("sell_tax_bps")),
            "status": "available" if payload.include_risk else "unavailable",
            "note": _first_non_empty(risk_data.get("note"), token_data.get("risk_note")),
        }
        holders_data = _section_dict(holders_raw)
        holder_items = _section_list(holders_raw, "holders", "items", "token_holders", "results")
        holder_snapshot = {
            "holder_count": _first_non_empty(holders_data.get("holder_count"), token_data.get("holder_count")),
            "top_holder_share_pct": _first_non_empty(holders_data.get("top_holder_share_pct"), token_data.get("top_holder_share_pct")),
            "holders": [
                {
                    "holder_address": _first_non_empty(item.get("holder_address"), item.get("address"), item.get("wallet_address")),
                    "quantity": _first_non_empty(item.get("quantity"), item.get("balance")),
                    "value_usd": _first_non_empty(item.get("value_usd"), item.get("usd_value")),
                    "share_pct": _first_non_empty(item.get("share_pct"), item.get("percentage")),
                    "label": _first_non_empty(item.get("label"), item.get("name")),
                }
                for item in holder_items
                if isinstance(item, dict)
            ],
            "status": "available" if payload.include_holders else "unavailable",
            "note": None if payload.include_holders else "holder data disabled by request",
        }
        main_pair_data = _first_non_empty(token_data.get("main_pair_ref"), token_data.get("pair"), token_data.get("pair_ref"))
        if isinstance(main_pair_data, dict):
            main_pair_ref = _pair_reference(main_pair_data, fallback_token=identity, fallback_chain=chain)
        else:
            main_pair_ref = {
                "identifier": f"{_first_non_empty(identity.get('symbol'), identity.get('identifier'))}/USDT",
                "chain": chain,
                "pair_address": _first_non_empty(token_data.get("main_pair_address"), token_data.get("pair_address")),
                "dex": _first_non_empty(token_data.get("dex"), token_data.get("pair_dex")),
                "base_token_ref": identity,
                "quote_token_ref": {
                    "identifier": f"{chain}:USDT" if chain else "USDT",
                    "chain": chain,
                    "token_address": None,
                    "symbol": "USDT",
                    "name": "Tether USD",
                    "source": "ave",
                },
            }
        return {
            "identity": identity,
            "market_snapshot": market_snapshot,
            "risk_snapshot": risk_snapshot,
            "holder_snapshot": holder_snapshot,
            "main_pair_ref": main_pair_ref,
            "source_meta": _source_meta(token_raw, command="token", provider=self.name),
        }

    def inspect_market(self, payload: InspectMarketRequest) -> dict[str, Any]:
        token_address = self._resolve_token_address(payload)
        chain = self._resolve_chain(payload.token_ref)
        pair_ref = payload.pair_ref
        if pair_ref is not None and pair_ref.pair_address:
            pair_address = pair_ref.pair_address
            pair_identifier = pair_ref.identifier
        else:
            token_detail = self._cli.run_json("token", "--address", token_address, "--chain", chain)
            token_data = _section_dict(token_detail)
            token_identity = _token_reference(
                {
                    **token_data,
                    "identifier": _first_non_empty(token_data.get("identifier"), payload.token_ref.identifier),
                    "chain": _first_non_empty(token_data.get("chain"), chain),
                    "token_address": _first_non_empty(token_data.get("token_address"), token_address),
                    "symbol": _first_non_empty(token_data.get("symbol"), payload.token_ref.symbol),
                    "name": _first_non_empty(token_data.get("name"), payload.token_ref.name),
                    "source": _first_non_empty(token_data.get("source"), "ave"),
                },
                chain=chain,
                fallback_source="ave",
            )
            pair_candidate = _first_non_empty(token_data.get("main_pair_ref"), token_data.get("pair"), token_data.get("pair_ref"))
            if isinstance(pair_candidate, dict):
                pair_ref = _pair_reference(pair_candidate, fallback_token=token_identity, fallback_chain=chain)
            else:
                pair_ref = None
            pair_address = _first_non_empty(
                _as_dict(token_data.get("main_pair_ref")).get("pair_address"),
                token_data.get("main_pair_address"),
                token_data.get("pair_address"),
                f"{_first_non_empty(token_identity.get('symbol'), token_identity.get('identifier'))}/USDT",
            )
            pair_identifier = _first_non_empty(
                _as_dict(token_data.get("main_pair_ref")).get("identifier"),
                token_data.get("pair_identifier"),
                f"{_first_non_empty(token_identity.get('symbol'), token_identity.get('identifier'))}/USDT",
            )
        pair_raw = self._cli.run_json("pair", "--address", pair_address, "--chain", chain)
        kline_raw = self._cli.run_json("kline-pair", "--address", pair_address, "--chain", chain, "--interval", "60", "--size", "24")
        swaps_raw = self._cli.run_json("txs", "--address", pair_address, "--chain", chain)
        pair_data = _section_dict(pair_raw)
        kline_data = _section_dict(kline_raw)
        swap_items = _section_list(swaps_raw, "recent_swaps", "items", "txs", "swaps", "data")
        selected_pair = _pair_reference(
            {
                **pair_data,
                "identifier": _first_non_empty(pair_data.get("identifier"), pair_identifier),
                "chain": _first_non_empty(pair_data.get("chain"), chain),
                "pair_address": _first_non_empty(pair_data.get("pair_address"), pair_address),
                "dex": _first_non_empty(pair_data.get("dex"), pair_data.get("source")),
            },
            fallback_token=payload.token_ref.model_dump(mode="json"),
            fallback_chain=chain,
        )
        points = _section_list(kline_raw, "points", "ohlcv", "candles")
        normalized_points = _normalize_timestamp_points(points)
        recent_swaps = [
            {
                "tx_hash": _first_non_empty(item.get("tx_hash"), item.get("hash"), item.get("transaction_hash")),
                "timestamp": _first_non_empty(item.get("timestamp"), item.get("time"), utc_now()),
                "side": _first_non_empty(item.get("side"), item.get("type"), "unknown"),
                "token_ref": _token_reference(
                    _as_dict(item.get("token_ref")),
                    chain=chain,
                    fallback_source="ave",
                )
                if isinstance(item.get("token_ref"), dict)
                else None,
                "amount_base": _first_non_empty(item.get("amount_base"), item.get("base_amount")),
                "amount_quote": _first_non_empty(item.get("amount_quote"), item.get("quote_amount")),
                "trader": _first_non_empty(item.get("trader"), item.get("sender"), item.get("wallet")),
            }
            for item in swap_items
            if isinstance(item, dict)
        ]
        flow_summary = _as_dict(_first_non_empty(pair_data.get("flow_summary"), kline_data.get("flow_summary")))
        if not flow_summary:
            flow_summary = {
                "buy_count": sum(1 for item in recent_swaps if item.get("side") == "buy"),
                "sell_count": sum(1 for item in recent_swaps if item.get("side") == "sell"),
                "net_flow_usd": None,
                "large_trade_count": None,
                "note": f"{payload.window} window at {payload.interval} interval",
            }
        return {
            "selected_pair": selected_pair,
            "ohlcv": normalized_points,
            "recent_swaps": recent_swaps,
            "flow_summary": flow_summary,
            "source_meta": _source_meta(pair_raw, command="pair", provider=self.name),
        }

    def inspect_wallet(self, payload: InspectWalletRequest) -> dict[str, Any]:
        chain = payload.chain or "unknown"
        wallet_info_raw = self._cli.run_json("wallet-info", "--wallet", payload.wallet, "--chain", chain)
        wallet_tokens_raw = self._cli.run_json("wallet-tokens", "--wallet", payload.wallet, "--chain", chain)
        activity_raw = self._cli.run_json("address-txs", "--wallet", payload.wallet, "--chain", chain)
        wallet_info = _section_dict(wallet_info_raw)
        wallet_tokens = _section_list(wallet_tokens_raw, "tokens", "items", "holdings", "rows")
        activities = _section_list(activity_raw, "items", "txs", "activity", "records")
        wallet_summary = {
            "wallet_address": _first_non_empty(wallet_info.get("wallet_address"), payload.wallet),
            "chain": _first_non_empty(wallet_info.get("chain"), chain),
            "label": _first_non_empty(wallet_info.get("label"), wallet_info.get("name")),
            "balance_usd": _first_non_empty(wallet_info.get("balance_usd"), wallet_info.get("total_value_usd")),
            "token_count": _first_non_empty(wallet_info.get("token_count"), len(wallet_tokens)),
            "status": "available",
            "note": _first_non_empty(wallet_info.get("note"), None),
        }
        holdings = [
            {
                "token_ref": _token_reference(_as_dict(item.get("token_ref")), chain=chain, fallback_source="ave")
                if isinstance(item, dict)
                else None,
                "quantity": _first_non_empty(item.get("quantity"), item.get("balance")),
                "value_usd": _first_non_empty(item.get("value_usd"), item.get("usd_value"), item.get("value")),
                "allocation_pct": _first_non_empty(item.get("allocation_pct"), item.get("share_pct"), item.get("percentage")),
            }
            for item in wallet_tokens
            if isinstance(item, dict)
        ]
        recent_activity = [
            {
                "tx_hash": _first_non_empty(item.get("tx_hash"), item.get("hash"), item.get("transaction_hash")),
                "timestamp": _first_non_empty(item.get("timestamp"), item.get("time"), utc_now()),
                "action": _first_non_empty(item.get("action"), item.get("side"), item.get("type"), "unknown"),
                "token_ref": _token_reference(_as_dict(item.get("token_ref")), chain=chain, fallback_source="ave")
                if isinstance(item.get("token_ref"), dict)
                else None,
                "amount_usd": _first_non_empty(item.get("amount_usd"), item.get("value_usd")),
                "note": _first_non_empty(item.get("note"), item.get("description")),
            }
            for item in activities
            if isinstance(item, dict)
        ]
        return {
            "wallet_summary": wallet_summary,
            "holdings": holdings if payload.include_holdings else [],
            "recent_activity": recent_activity if payload.include_activity else [],
            "source_meta": _source_meta(wallet_info_raw, command="wallet-info", provider=self.name),
        }

    def review_signals(self, payload: ReviewSignalsRequest) -> dict[str, Any]:
        chain = payload.chain or (payload.token_ref.chain if payload.token_ref else "solana")
        raw = self._cli.run_json("signals", "--chain", chain, "--page-size", str(payload.limit), "--page-no", "1")
        section = _section_dict(raw)
        signals = _section_list(raw, "signals", "items", "results")
        linked_refs = []
        if payload.token_ref is not None:
            linked_refs.append(_token_reference(payload.token_ref.model_dump(mode="json"), chain=chain, fallback_source="ave"))
        for item in signals:
            if isinstance(item, dict) and isinstance(item.get("token_ref"), dict):
                linked_refs.append(_token_reference(item["token_ref"], chain=chain, fallback_source="ave"))
        deduped_linked_refs: list[dict[str, Any]] = []
        seen_ids: set[str] = set()
        for token_ref in linked_refs:
            identifier = token_ref.get("identifier")
            if identifier in seen_ids:
                continue
            seen_ids.add(identifier)
            deduped_linked_refs.append(token_ref)
        normalized_signals = [
            {
                "signal_id": _first_non_empty(item.get("signal_id"), item.get("id"), item.get("title")),
                "title": _first_non_empty(item.get("title"), item.get("name"), "AVE signal"),
                "severity": _first_non_empty(item.get("severity"), "medium"),
                "chain": _first_non_empty(item.get("chain"), chain),
                "token_ref": _token_reference(item.get("token_ref"), chain=chain, fallback_source="ave")
                if isinstance(item.get("token_ref"), dict)
                else (payload.token_ref.model_dump(mode="json") if payload.token_ref else None),
                "description": _first_non_empty(item.get("description"), item.get("note")),
                "occurred_at": _first_non_empty(item.get("occurred_at"), item.get("timestamp"), utc_now()),
                "source": _first_non_empty(item.get("source"), "ave"),
            }
            for item in signals
            if isinstance(item, dict)
        ]
        return {
            "signals": normalized_signals[: payload.limit],
            "linked_token_refs": deduped_linked_refs,
            "source_meta": _source_meta(raw, command="signals", provider=self.name),
        }


def build_provider() -> ProviderAdapter:
    mode = os.environ.get("AVE_DATA_PROVIDER", "").strip().lower()
    if not mode:
        mode = "auto" if os.environ.get("AVE_API_KEY") else "mock"
    if mode in {"ave_rest", "real"}:
        script_path = Path(os.environ.get("AVE_REST_SCRIPT_PATH", DEFAULT_VENDOR_SCRIPT)).expanduser()
        python_executable = os.environ.get("AVE_REST_PYTHON", sys.executable)
        timeout_seconds = float(os.environ.get("AVE_REST_TIMEOUT_SECONDS", "30.0"))
        return AveRestProvider(script_path=script_path, python_executable=python_executable, timeout_seconds=timeout_seconds)
    if mode == "auto":
        script_path = Path(os.environ.get("AVE_REST_SCRIPT_PATH", DEFAULT_VENDOR_SCRIPT)).expanduser()
        if script_path.exists():
            python_executable = os.environ.get("AVE_REST_PYTHON", sys.executable)
            timeout_seconds = float(os.environ.get("AVE_REST_TIMEOUT_SECONDS", "30.0"))
            return AveRestProvider(script_path=script_path, python_executable=python_executable, timeout_seconds=timeout_seconds)
    return MockProvider()


def provider_error(message: str, *, status_code: int = 500, details: dict[str, Any] | None = None) -> ServiceError:
    return ServiceError(
        code=ErrorCode.PROVIDER_ERROR,
        message=message,
        status_code=status_code,
        details=details or {},
    )
