from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import timedelta
from pathlib import Path
from typing import Any, Protocol

import httpx

from errors import ErrorCode, ServiceError
from models import (
    DiscoverTokensRequest,
    InspectMarketRequest,
    InspectTokenRequest,
    InspectWalletRequest,
    ProviderName,
    ReviewSignalsRequest,
)
from ot_skill_enterprise.shared.contracts.common import utc_now


DEFAULT_VENDOR_SCRIPT = (
    Path(__file__).resolve().parents[2] / "vendor" / "ave_cloud_skill" / "scripts" / "ave_data_rest.py"
)

_PLACEHOLDER_TEXT = {"", "--", "none", "null", "unknown", "token", "n/a"}
_STABLE_SYMBOLS = {"USDT", "USDC", "DAI", "FDUSD", "TUSD"}
_QUOTE_SYMBOLS = _STABLE_SYMBOLS | {"WBNB", "BNB", "WETH", "ETH"}
_EVM_ADDRESS_RE = re.compile(r"^0x[a-fA-F0-9]{40}$")
_EVM_CHAINS = {
    "ethereum",
    "eth",
    "bsc",
    "base",
    "arbitrum",
    "optimism",
    "polygon",
    "avalanche",
    "avax",
    "fantom",
    "celo",
    "linea",
    "blast",
    "zksync",
}


class ProviderAdapter(Protocol):
    name: ProviderName

    def discover_tokens(self, payload: DiscoverTokensRequest) -> dict[str, Any]: ...

    def inspect_token(self, payload: InspectTokenRequest) -> dict[str, Any]: ...

    def inspect_market(self, payload: InspectMarketRequest) -> dict[str, Any]: ...

    def inspect_wallet(self, payload: InspectWalletRequest) -> dict[str, Any]: ...

    def review_signals(self, payload: ReviewSignalsRequest) -> dict[str, Any]: ...


@dataclass(slots=True)
class MockProvider:
    name: ProviderName = ProviderName.MOCK

    def discover_tokens(self, payload: DiscoverTokensRequest) -> dict[str, Any]:
        base = (payload.query or payload.source or "ave").strip()
        symbol = base.upper()[:6] or "AVE"
        chain = payload.chain or "unknown"
        now = utc_now()
        return {
            "token_refs": [
                {
                    "identifier": f"{chain}:{symbol}",
                    "chain": chain,
                    "token_address": f"0x{symbol.lower():0<40}"[:42],
                    "symbol": symbol,
                    "name": f"{base.title()} Token",
                    "rank": 1,
                    "score": 92.0,
                    "source": payload.source or "mock",
                },
                {
                    "identifier": f"{chain}:{symbol}X",
                    "chain": chain,
                    "token_address": f"0x{(symbol + 'x').lower():0<40}"[:42],
                    "symbol": f"{symbol[:4]}X",
                    "name": f"{base.title()} Labs",
                    "rank": 2,
                    "score": 84.0,
                    "source": payload.source or "mock",
                },
            ][: payload.limit],
            "ranking_context": {
                "title": "Token discovery",
                "window": "24h",
                "source": payload.source or "mock",
                "note": "Generated by mock provider",
                "metadata": {"query": payload.query or "", "chain": chain},
            },
            "source_meta": {
                "provider": self.name,
                "request_id": payload.query or None,
                "fetched_at": now,
                "cached": False,
                "source_version": "mock-v1",
                "metadata": {"mode": "in-memory"},
            },
        }

    def inspect_token(self, payload: InspectTokenRequest) -> dict[str, Any]:
        token_ref = payload.token_ref
        symbol = token_ref.symbol or token_ref.identifier.upper()
        chain = token_ref.chain or "unknown"
        now = utc_now()
        return {
            "identity": {
                "identifier": token_ref.identifier,
                "chain": chain,
                "token_address": token_ref.token_address,
                "symbol": symbol,
                "name": f"{symbol} Protocol",
                "source": "mock",
            },
            "market_snapshot": {
                "price_usd": 1.2345,
                "market_cap_usd": 123_450_000,
                "fdv_usd": 234_500_000,
                "liquidity_usd": 8_750_000,
                "volume_24h_usd": 18_400_000,
                "status": "available",
            },
            "risk_snapshot": {
                "risk_level": "medium",
                "flags": ["mock-provider"],
                "honeypot": False,
                "buy_tax_bps": 0,
                "sell_tax_bps": 0,
                "status": "available",
            },
            "holder_snapshot": {
                "holder_count": 1280,
                "top_holder_share_pct": 27.0,
                "holders": [
                    {
                        "holder_address": "0x1111111111111111111111111111111111111111",
                        "quantity": 1500000,
                        "value_usd": 1850000,
                        "share_pct": 14.2,
                        "label": "mock-top-holder",
                    }
                ]
                if payload.include_holders
                else [],
                "status": "available" if payload.include_holders else "unavailable",
                "note": None if payload.include_holders else "holder data disabled by request",
            },
            "main_pair_ref": {
                "identifier": f"{symbol}/USDT",
                "chain": chain,
                "pair_address": "0xpair000000000000000000000000000000000001",
                "dex": "mockswap",
                "base_token_ref": {
                    "identifier": token_ref.identifier,
                    "chain": chain,
                    "token_address": token_ref.token_address,
                    "symbol": symbol,
                    "name": f"{symbol} Protocol",
                    "source": "mock",
                },
                "quote_token_ref": {
                    "identifier": f"{chain}:USDT",
                    "chain": chain,
                    "symbol": "USDT",
                    "name": "Tether USD",
                    "source": "mock",
                },
            },
            "source_meta": {
                "provider": self.name,
                "fetched_at": now,
                "cached": False,
                "source_version": "mock-v1",
            },
        }

    def inspect_market(self, payload: InspectMarketRequest) -> dict[str, Any]:
        token_ref = payload.token_ref
        symbol = token_ref.symbol or token_ref.identifier.upper()
        chain = token_ref.chain or "unknown"
        pair_identifier = payload.pair_ref.identifier if payload.pair_ref is not None else f"{symbol}/USDT"
        now = utc_now()
        points = []
        for idx in range(4):
            timestamp = now - timedelta(hours=idx)
            base = 1.0 + idx * 0.01
            points.append(
                {
                    "timestamp": timestamp,
                    "open": base,
                    "high": base + 0.02,
                    "low": max(base - 0.01, 0),
                    "close": base + 0.01,
                    "volume": 1000 + idx * 50,
                }
            )
        return {
            "selected_pair": {
                "identifier": pair_identifier,
                "chain": chain,
                "pair_address": payload.pair_ref.pair_address if payload.pair_ref is not None else "0xpair000000000000000000000000000000000002",
                "dex": "mockswap",
                "base_token_ref": {
                    "identifier": token_ref.identifier,
                    "chain": chain,
                    "token_address": token_ref.token_address,
                    "symbol": symbol,
                    "name": f"{symbol} Protocol",
                    "source": "mock",
                },
                "quote_token_ref": {
                    "identifier": f"{chain}:USDT",
                    "chain": chain,
                    "symbol": "USDT",
                    "name": "Tether USD",
                    "source": "mock",
                },
            },
            "ohlcv": list(reversed(points)),
            "recent_swaps": [
                {
                    "tx_hash": "0xmock1",
                    "timestamp": now - timedelta(minutes=5),
                    "side": "buy",
                    "token_ref": {
                        "identifier": token_ref.identifier,
                        "chain": chain,
                        "symbol": symbol,
                        "source": "mock",
                    },
                    "amount_base": 1200,
                    "amount_quote": 1450,
                    "trader": "0xtrader1",
                },
                {
                    "tx_hash": "0xmock2",
                    "timestamp": now - timedelta(minutes=1),
                    "side": "sell",
                    "token_ref": {
                        "identifier": token_ref.identifier,
                        "chain": chain,
                        "symbol": symbol,
                        "source": "mock",
                    },
                    "amount_base": 860,
                    "amount_quote": 1035,
                    "trader": "0xtrader2",
                },
            ],
            "flow_summary": {
                "buy_count": 14,
                "sell_count": 9,
                "net_flow_usd": 3400,
                "large_trade_count": 2,
                "note": f"{payload.window} window at {payload.interval} interval",
            },
            "source_meta": {
                "provider": self.name,
                "fetched_at": now,
                "cached": False,
                "source_version": "mock-v1",
            },
        }

    def inspect_wallet(self, payload: InspectWalletRequest) -> dict[str, Any]:
        chain = payload.chain or "unknown"
        now = utc_now()
        return {
            "wallet_summary": {
                "wallet_address": payload.wallet,
                "chain": chain,
                "label": "mock-wallet",
                "balance_usd": 7740,
                "token_count": 2,
                "status": "available",
            },
            "holdings": [
                {
                    "token_ref": {
                        "identifier": f"{chain}:AVE",
                        "chain": chain,
                        "symbol": "AVE",
                        "name": "Ave Token",
                        "source": "mock",
                    },
                    "quantity": 1200,
                    "value_usd": 2340,
                    "allocation_pct": 30.2,
                },
                {
                    "token_ref": {
                        "identifier": f"{chain}:USDT",
                        "chain": chain,
                        "symbol": "USDT",
                        "name": "Tether USD",
                        "source": "mock",
                    },
                    "quantity": 5400,
                    "value_usd": 5400,
                    "allocation_pct": 69.8,
                },
            ]
            if payload.include_holdings
            else [],
            "recent_activity": [
                {
                    "tx_hash": "0xwallet1",
                    "timestamp": now - timedelta(minutes=10),
                    "action": "swap",
                    "token_ref": {
                        "identifier": f"{chain}:AVE",
                        "chain": chain,
                        "symbol": "AVE",
                        "name": "Ave Token",
                        "source": "mock",
                    },
                    "amount_usd": 1800,
                    "note": "mock swap",
                },
                {
                    "tx_hash": "0xwallet2",
                    "timestamp": now - timedelta(minutes=3),
                    "action": "transfer",
                    "token_ref": {
                        "identifier": f"{chain}:USDT",
                        "chain": chain,
                        "symbol": "USDT",
                        "name": "Tether USD",
                        "source": "mock",
                    },
                    "amount_usd": 3200,
                    "note": "mock transfer",
                },
            ]
            if payload.include_activity
            else [],
            "source_meta": {
                "provider": self.name,
                "fetched_at": now,
                "cached": False,
                "source_version": "mock-v1",
            },
        }

    def review_signals(self, payload: ReviewSignalsRequest) -> dict[str, Any]:
        chain = payload.chain or "unknown"
        token_ref = payload.token_ref
        token_identifier = token_ref.identifier if token_ref is not None else f"{chain}:ALPHA"
        symbol = token_ref.symbol if token_ref is not None and token_ref.symbol else token_identifier.split(":")[-1].upper()
        now = utc_now()
        return {
            "signals": [
                {
                    "signal_id": "signal-001",
                    "title": f"{symbol} volume spike",
                    "severity": "high",
                    "chain": chain,
                    "token_ref": {
                        "identifier": token_identifier,
                        "chain": chain,
                        "symbol": symbol,
                        "source": "mock",
                    },
                    "description": "Detected accelerated buy pressure across tracked pools.",
                    "occurred_at": now - timedelta(minutes=8),
                    "source": "mock",
                },
                {
                    "signal_id": "signal-002",
                    "title": f"{symbol} wallet clustering",
                    "severity": "medium",
                    "chain": chain,
                    "token_ref": {
                        "identifier": token_identifier,
                        "chain": chain,
                        "symbol": symbol,
                        "source": "mock",
                    },
                    "description": "Linked wallet cluster accumulated into the same pair.",
                    "occurred_at": now - timedelta(minutes=2),
                    "source": "mock",
                },
            ][: payload.limit],
            "linked_token_refs": [
                {
                    "identifier": token_identifier,
                    "chain": chain,
                    "symbol": symbol,
                    "source": "mock",
                }
            ],
            "source_meta": {
                "provider": self.name,
                "fetched_at": now,
                "cached": False,
                "source_version": "mock-v1",
            },
        }


def _as_dict(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _as_list(value: Any) -> list[Any]:
    return value if isinstance(value, list) else []


def _data_section(payload: dict[str, Any]) -> Any:
    data = payload.get("data")
    return payload if data is None else data


def _section_dict(payload: dict[str, Any]) -> dict[str, Any]:
    section = _data_section(payload)
    return section if isinstance(section, dict) else payload


def _nested_dict(payload: dict[str, Any], *keys: str) -> dict[str, Any]:
    current: Any = payload
    for key in keys:
        if not isinstance(current, dict):
            return {}
        current = current.get(key)
    return current if isinstance(current, dict) else {}


def _section_list(payload: dict[str, Any], *keys: str) -> list[Any]:
    section = _data_section(payload)
    if isinstance(section, dict):
        for key in keys:
            value = section.get(key)
            if isinstance(value, list):
                return value
    if isinstance(section, list):
        return section
    for key in keys:
        value = payload.get(key)
        if isinstance(value, list):
            return value
    return []


def _first_non_empty(*values: Any) -> Any:
    for value in values:
        if value is None:
            continue
        if isinstance(value, str) and not value.strip():
            continue
        return value
    return None


def _safe_float(value: Any) -> float | None:
    if value is None:
        return None
    if isinstance(value, str):
        text = value.strip()
        if not text or text.lower() in _PLACEHOLDER_TEXT:
            return None
        value = text
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _normalized_text(value: Any) -> str | None:
    text = str(value or "").strip()
    if not text or text.lower() in _PLACEHOLDER_TEXT:
        return None
    return text


def _normalize_symbol(value: Any) -> str | None:
    text = _normalized_text(value)
    return text if text is None else text.strip()


def _is_evm_address(value: Any) -> bool:
    text = _normalized_text(value)
    return bool(text and _EVM_ADDRESS_RE.fullmatch(text))


def _is_evm_chain(value: Any) -> bool:
    text = _normalized_text(value)
    return bool(text and text.lower() in _EVM_CHAINS)


def _canonical_token_address(value: Any) -> str | None:
    text = _normalized_text(value)
    if text is None:
        return None
    return text.lower() if _is_evm_address(text) else None


def _is_quote_symbol(value: Any) -> bool:
    symbol = _normalize_symbol(value)
    return bool(symbol and symbol.upper() in _QUOTE_SYMBOLS)


def _estimate_amount_usd(*, amount: Any, price: Any) -> float | None:
    amount_value = _safe_float(amount)
    price_value = _safe_float(price)
    if amount_value is None or price_value is None:
        return None
    return round(amount_value * price_value, 8)


def _normalize_pair_candidate(
    entry: dict[str, Any],
    *,
    chain: str,
    fallback_token: dict[str, Any],
) -> dict[str, Any]:
    pair_address = _first_non_empty(entry.get("pair_address"), entry.get("pair"), entry.get("address"))
    token0_symbol = _normalize_symbol(entry.get("token0_symbol"))
    token1_symbol = _normalize_symbol(entry.get("token1_symbol"))
    token0_address = _canonical_token_address(entry.get("token0_address"))
    token1_address = _canonical_token_address(entry.get("token1_address"))
    target_token_address = _canonical_token_address(
        _first_non_empty(entry.get("target_token"), fallback_token.get("token_address"))
    )
    if target_token_address and token0_address == target_token_address:
        base_token = {
            "identifier": f"{chain}:{token0_address}",
            "chain": chain,
            "token_address": token0_address,
            "symbol": token0_symbol,
            "name": token0_symbol,
            "source": "ave",
        }
        quote_token = {
            "identifier": f"{chain}:{token1_address}" if token1_address else f"{chain}:{token1_symbol or 'QUOTE'}",
            "chain": chain,
            "token_address": token1_address,
            "symbol": token1_symbol,
            "name": token1_symbol,
            "source": "ave",
        }
    elif target_token_address and token1_address == target_token_address:
        base_token = {
            "identifier": f"{chain}:{token1_address}",
            "chain": chain,
            "token_address": token1_address,
            "symbol": token1_symbol,
            "name": token1_symbol,
            "source": "ave",
        }
        quote_token = {
            "identifier": f"{chain}:{token0_address}" if token0_address else f"{chain}:{token0_symbol or 'QUOTE'}",
            "chain": chain,
            "token_address": token0_address,
            "symbol": token0_symbol,
            "name": token0_symbol,
            "source": "ave",
        }
    else:
        base_token = fallback_token
        quote_token = {
            "identifier": f"{chain}:USDT" if chain else "USDT",
            "chain": chain,
            "token_address": None,
            "symbol": "USDT",
            "name": "Tether USD",
            "source": "ave",
        }
    identifier = _first_non_empty(
        entry.get("identifier"),
        entry.get("pair_identifier"),
        f"{_first_non_empty(base_token.get('symbol'), fallback_token.get('symbol'), 'TOKEN')}/{_first_non_empty(quote_token.get('symbol'), 'USDT')}",
    )
    return {
        "identifier": identifier,
        "chain": chain,
        "pair_address": pair_address,
        "dex": _first_non_empty(entry.get("dex"), entry.get("amm"), entry.get("source")),
        "base_token_ref": base_token,
        "quote_token_ref": quote_token,
        "liquidity_usd": _first_non_empty(entry.get("liquidity_usd"), entry.get("tvl")),
        "volume_24h_usd": _first_non_empty(entry.get("volume_24h_usd"), entry.get("volume_u_24h"), entry.get("volume_u")),
        "price_change_1h": _first_non_empty(entry.get("price_change_1h"), entry.get("token_price_change_1h")),
        "price_change_24h": _first_non_empty(entry.get("price_change_24h"), entry.get("price_change_1d"), entry.get("token_price_change_24h")),
        "price_usd": _first_non_empty(entry.get("price_usd"), entry.get("token1_price_usd"), entry.get("token0_price_usd")),
    }


def _best_pair_candidate(
    token_payload: dict[str, Any],
    pair_items: list[dict[str, Any]],
    *,
    chain: str,
    fallback_token: dict[str, Any],
) -> dict[str, Any]:
    main_pair = _canonical_token_address(token_payload.get("main_pair"))
    normalized = [
        _normalize_pair_candidate(item, chain=chain, fallback_token=fallback_token)
        for item in pair_items
        if isinstance(item, dict)
    ]
    if main_pair:
        for item in normalized:
            if _canonical_token_address(item.get("pair_address")) == main_pair:
                return item
    if normalized:
        normalized.sort(
            key=lambda item: (
                _safe_float(item.get("liquidity_usd")) or 0.0,
                _safe_float(item.get("volume_24h_usd")) or 0.0,
            ),
            reverse=True,
        )
        return normalized[0]
    return {}


def _activity_note(*, action: str, from_symbol: str | None, to_symbol: str | None) -> str:
    left = from_symbol or "unknown"
    right = to_symbol or "unknown"
    return f"{action}:{left}->{right}"


def _token_identifier(chain: str | None, entry: dict[str, Any]) -> str:
    token_address = _canonical_token_address(
        _first_non_empty(entry.get("token_address"), entry.get("address"), entry.get("token"))
    )
    if token_address is not None:
        return f"{chain}:{token_address}" if chain else token_address
    symbol_or_name = _first_non_empty(_normalize_symbol(entry.get("symbol")), _normalized_text(entry.get("name")), "unknown")
    return str(
        _first_non_empty(
            entry.get("identifier"),
            entry.get("token_id"),
            entry.get("token_identifier"),
            f"{chain}:{symbol_or_name}" if chain else symbol_or_name,
        )
    )


def _token_reference(entry: dict[str, Any], *, chain: str | None = None, fallback_source: str | None = None) -> dict[str, Any]:
    entry_chain = _first_non_empty(entry.get("chain"), chain)
    identifier = _token_identifier(entry_chain, entry)
    symbol = _first_non_empty(_normalize_symbol(entry.get("symbol")), _normalize_symbol(entry.get("token_symbol")))
    name = _first_non_empty(_normalized_text(entry.get("name")), _normalized_text(entry.get("token_name")))
    token_address = _canonical_token_address(_first_non_empty(entry.get("token_address"), entry.get("address"), entry.get("token")))
    if token_address is None and identifier and ":" in identifier:
        suffix = identifier.split(":", 1)[1]
        token_address = _canonical_token_address(suffix)
    return {
        "identifier": identifier,
        "chain": entry_chain,
        "token_address": token_address,
        "symbol": symbol,
        "name": name,
        "rank": entry.get("rank"),
        "score": entry.get("score"),
        "source": _first_non_empty(entry.get("source"), fallback_source),
    }


def _pair_reference(entry: dict[str, Any], *, fallback_token: dict[str, Any], fallback_chain: str | None = None) -> dict[str, Any]:
    chain = _first_non_empty(entry.get("chain"), fallback_chain, fallback_token.get("chain"))
    identifier = _first_non_empty(entry.get("identifier"), entry.get("pair_identifier"))
    if identifier is None:
        token_symbol = _first_non_empty(fallback_token.get("symbol"), fallback_token.get("identifier"), "TOKEN")
        identifier = f"{token_symbol}/USDT"
    base_token_ref = _first_non_empty(entry.get("base_token_ref"), entry.get("base_token"), fallback_token)
    if not isinstance(base_token_ref, dict):
        base_token_ref = fallback_token
    quote_token_ref = _first_non_empty(entry.get("quote_token_ref"), entry.get("quote_token"))
    if not isinstance(quote_token_ref, dict):
        quote_token_ref = {
            "identifier": _first_non_empty(entry.get("quote_identifier"), f"{chain}:USDT" if chain else "USDT"),
            "chain": chain,
            "token_address": None,
            "symbol": "USDT",
            "name": "Tether USD",
            "source": "ave",
        }
    return {
        "identifier": identifier,
        "chain": chain,
        "pair_address": _first_non_empty(entry.get("pair_address"), entry.get("address")),
        "dex": _first_non_empty(entry.get("dex"), entry.get("amm"), entry.get("source")),
        "base_token_ref": base_token_ref,
        "quote_token_ref": quote_token_ref,
    }


def _source_meta(payload: dict[str, Any], *, command: str, provider: ProviderName, request_id: str | None = None) -> dict[str, Any]:
    section = _section_dict(payload)
    raw_meta = _as_dict(payload.get("meta"))
    raw_top_source_meta = _as_dict(payload.get("source_meta"))
    raw_source_meta = _as_dict(section.get("source_meta"))
    return {
        "provider": provider,
        "request_id": _first_non_empty(
            request_id,
            raw_source_meta.get("request_id"),
            raw_top_source_meta.get("request_id"),
            raw_meta.get("request_id"),
            payload.get("request_id"),
        ),
        "fetched_at": _first_non_empty(
            raw_source_meta.get("fetched_at"),
            raw_top_source_meta.get("fetched_at"),
            raw_meta.get("fetched_at"),
            payload.get("fetched_at"),
            utc_now(),
        ),
        "cached": bool(_first_non_empty(raw_source_meta.get("cached"), raw_top_source_meta.get("cached"), raw_meta.get("cached"), False)),
        "source_version": _first_non_empty(
            raw_source_meta.get("source_version"),
            raw_top_source_meta.get("source_version"),
            raw_meta.get("source_version"),
            f"vendored-cli:{command}",
        ),
        "metadata": {
            **_as_dict(raw_meta.get("metadata")),
            **_as_dict(raw_top_source_meta.get("metadata")),
            **_as_dict(raw_source_meta.get("metadata")),
            "command": command,
        },
    }


def _normalize_cli_payload(payload: Any) -> dict[str, Any]:
    if not isinstance(payload, dict):
        raise ServiceError(
            code=ErrorCode.PROVIDER_ERROR,
            message="AVE CLI returned a non-JSON object",
            status_code=502,
            details={"payload_type": type(payload).__name__},
        )
    return payload


def _normalize_timestamp_points(points: list[Any]) -> list[Any]:
    if not isinstance(points, list):
        return []
    normalized: list[Any] = []
    for item in points:
        if isinstance(item, dict):
            normalized.append(item)
    return normalized


def _normalize_wallet_token_item(item: dict[str, Any], *, chain: str, total_balance_usd: float | None) -> dict[str, Any]:
    token_address = _canonical_token_address(_first_non_empty(item.get("token"), item.get("token_address"), item.get("address")))
    symbol = _normalize_symbol(item.get("symbol"))
    balance_usd = _safe_float(_first_non_empty(item.get("balance_usd"), item.get("usd_value"), item.get("value")))
    allocation_pct = _safe_float(_first_non_empty(item.get("allocation_pct"), item.get("share_pct"), item.get("percentage")))
    if allocation_pct is None and total_balance_usd and total_balance_usd > 0 and balance_usd is not None:
        allocation_pct = round((balance_usd / total_balance_usd) * 100.0, 4)
    token_ref = _token_reference(
        {
            "chain": chain,
            "token": token_address,
            "token_address": token_address,
            "identifier": f"{chain}:{token_address}" if token_address else f"{chain}:{symbol or 'unknown'}",
            "symbol": symbol,
            "name": _normalized_text(item.get("name")) or symbol,
            "source": "ave",
        },
        chain=chain,
        fallback_source="ave",
    )
    return {
        "token_ref": token_ref,
        "quantity": _first_non_empty(item.get("balance_amount"), item.get("quantity"), item.get("balance")),
        "value_usd": balance_usd,
        "allocation_pct": allocation_pct,
        "metadata": {
            "risk_level": item.get("risk_level"),
            "risk_score": item.get("risk_score"),
            "total_profit": item.get("total_profit"),
            "total_profit_ratio": item.get("total_profit_ratio"),
            "total_purchase_usd": item.get("total_purchase_usd"),
            "total_sold_usd": item.get("total_sold_usd"),
            "total_purchase": item.get("total_purchase"),
            "total_sold": item.get("total_sold"),
            "current_price_usd": item.get("current_price_usd"),
            "main_token_symbol": item.get("main_token_symbol"),
        },
    }


def _normalize_wallet_activity_item(item: dict[str, Any], *, chain: str) -> dict[str, Any]:
    from_symbol = _normalize_symbol(item.get("from_symbol"))
    to_symbol = _normalize_symbol(item.get("to_symbol"))
    from_ref = _token_reference(
        {
            "chain": chain,
            "token": item.get("from_address"),
            "token_address": item.get("from_address"),
            "identifier": f"{chain}:{_canonical_token_address(item.get('from_address'))}" if _canonical_token_address(item.get("from_address")) else f"{chain}:{from_symbol or 'unknown'}",
            "symbol": from_symbol,
            "name": from_symbol,
            "source": "ave",
        },
        chain=chain,
        fallback_source="ave",
    )
    to_ref = _token_reference(
        {
            "chain": chain,
            "token": item.get("to_address"),
            "token_address": item.get("to_address"),
            "identifier": f"{chain}:{_canonical_token_address(item.get('to_address'))}" if _canonical_token_address(item.get("to_address")) else f"{chain}:{to_symbol or 'unknown'}",
            "symbol": to_symbol,
            "name": to_symbol,
            "source": "ave",
        },
        chain=chain,
        fallback_source="ave",
    )
    from_is_quote = _is_quote_symbol(from_symbol)
    to_is_quote = _is_quote_symbol(to_symbol)
    from_amount_usd = _estimate_amount_usd(amount=item.get("from_amount"), price=item.get("from_price_usd"))
    to_amount_usd = _estimate_amount_usd(amount=item.get("to_amount"), price=item.get("to_price_usd"))
    amount_usd = _first_non_empty(to_amount_usd, from_amount_usd)

    action = "swap"
    token_ref = to_ref
    if not from_is_quote and to_is_quote:
        action = "sell"
        token_ref = from_ref
    elif from_is_quote and not to_is_quote:
        action = "buy"
        token_ref = to_ref
    elif not to_is_quote and to_ref.get("token_address"):
        action = "buy" if from_is_quote else "swap"
        token_ref = to_ref
    elif not from_is_quote and from_ref.get("token_address"):
        action = "sell" if to_is_quote else "swap"
        token_ref = from_ref
    elif from_ref.get("token_address"):
        token_ref = from_ref

    token_amount = None
    if action == "buy":
        token_amount = _safe_float(item.get("to_amount"))
    elif action == "sell":
        token_amount = _safe_float(item.get("from_amount"))

    return {
        "tx_hash": _first_non_empty(item.get("tx_hash"), item.get("hash"), item.get("transaction_hash"), item.get("transaction")),
        "timestamp": _first_non_empty(item.get("timestamp"), item.get("time"), utc_now()),
        "action": action,
        "token_ref": token_ref if isinstance(token_ref, dict) else None,
        "amount_usd": amount_usd,
        "token_amount": token_amount,
        "note": _first_non_empty(item.get("note"), item.get("description"), _activity_note(action=action, from_symbol=from_symbol, to_symbol=to_symbol)),
        "quote_symbol": to_symbol if action == "sell" else from_symbol,
        "quote_token_address": _canonical_token_address(item.get("to_address") if action == "sell" else item.get("from_address")),
        "from_symbol": from_symbol,
        "to_symbol": to_symbol,
        "from_token_address": _canonical_token_address(item.get("from_address")),
        "to_token_address": _canonical_token_address(item.get("to_address")),
        "from_amount": _safe_float(item.get("from_amount")),
        "to_amount": _safe_float(item.get("to_amount")),
    }


@dataclass(slots=True)
class _VendoredAveCli:
    script_path: Path = DEFAULT_VENDOR_SCRIPT
    python_executable: str = sys.executable
    timeout_seconds: float = 30.0

    def run_json(self, command: str, *args: str) -> dict[str, Any]:
        if not self.script_path.exists():
            raise ServiceError(
                code=ErrorCode.PROVIDER_UNAVAILABLE,
                message="Vendored AVE data-rest script is missing",
                status_code=503,
                details={"script_path": str(self.script_path)},
            )

        env = os.environ.copy()
        env.setdefault("AVE_IN_SERVER", "true")
        env.setdefault("AVE_USE_DOCKER", "false")

        completed = subprocess.run(
            [self.python_executable, str(self.script_path), command, *args],
            capture_output=True,
            text=True,
            env=env,
            timeout=self.timeout_seconds,
        )
        if completed.returncode != 0:
            stderr = (completed.stderr or completed.stdout or "").strip()
            raise ServiceError(
                code=ErrorCode.PROVIDER_ERROR,
                message=f"AVE CLI command failed: {command}",
                status_code=502,
                details={
                    "command": command,
                    "args": list(args),
                    "returncode": completed.returncode,
                    "stderr": stderr,
                    "script_path": str(self.script_path),
                },
            )

        output = (completed.stdout or "").strip()
        if not output:
            raise ServiceError(
                code=ErrorCode.PROVIDER_ERROR,
                message="AVE CLI returned empty output",
                status_code=502,
                details={"command": command, "args": list(args), "script_path": str(self.script_path)},
            )

        try:
            return _normalize_cli_payload(json.loads(output))
        except json.JSONDecodeError as exc:
            raise ServiceError(
                code=ErrorCode.PROVIDER_ERROR,
                message="AVE CLI returned invalid JSON",
                status_code=502,
                details={"command": command, "args": list(args), "stdout": output, "script_path": str(self.script_path)},
            ) from exc


@dataclass(slots=True)
class AveRestProvider:
    script_path: Path = DEFAULT_VENDOR_SCRIPT
    python_executable: str = sys.executable
    timeout_seconds: float = 10.0
    name: ProviderName = ProviderName.AVE_REST
    _cli: _VendoredAveCli = field(init=False, repr=False)

    def __post_init__(self) -> None:
        self._cli = _VendoredAveCli(
            script_path=self.script_path,
            python_executable=self.python_executable,
            timeout_seconds=self.timeout_seconds,
        )

    def _search(self, payload: DiscoverTokensRequest) -> dict[str, Any]:
        keyword = (payload.query or payload.source or payload.chain or "ave").strip()
        args = ["--keyword", keyword, "--limit", str(payload.limit)]
        if payload.chain:
            args.extend(["--chain", payload.chain])
        return self._cli.run_json("search", *args)

    def discover_tokens(self, payload: DiscoverTokensRequest) -> dict[str, Any]:
        raw = self._search(payload)
        section = _section_dict(raw)
        items = _section_list(raw, "token_refs", "items", "tokens", "results")
        token_refs = [_token_reference(_as_dict(item), chain=payload.chain, fallback_source=payload.source or "ave") for item in items]
        if not token_refs and isinstance(section, dict):
            token_refs = [_token_reference(section, chain=payload.chain, fallback_source=payload.source or "ave")]
        ranking_context = _as_dict(section.get("ranking_context"))
        if not ranking_context:
            ranking_context = {
                "title": _first_non_empty(section.get("title"), "Token discovery"),
                "window": _first_non_empty(section.get("window"), "24h"),
                "source": _first_non_empty(section.get("source"), payload.source, "ave"),
                "note": _first_non_empty(section.get("note"), "Vendored AVE CLI search result"),
                "metadata": {
                    "query": payload.query or "",
                    "chain": payload.chain or "",
                },
            }
        return {
            "token_refs": token_refs[: payload.limit],
            "ranking_context": ranking_context,
            "source_meta": _source_meta(raw, command="search", provider=self.name),
        }

    def _resolve_token_address(self, payload: DiscoverTokensRequest | InspectTokenRequest | InspectMarketRequest) -> str:
        token_ref = payload.token_ref
        chain = getattr(token_ref, "chain", None)
        if token_ref.token_address:
            candidate = _canonical_token_address(token_ref.token_address)
            if candidate is not None:
                return candidate
            if not _is_evm_chain(chain):
                return token_ref.token_address
        identifier = token_ref.identifier
        if ":" in identifier:
            suffix = identifier.split(":", 1)[1]
            candidate = _canonical_token_address(suffix)
            if candidate is not None:
                return candidate
            if not _is_evm_chain(chain):
                return suffix
        if "-" in identifier:
            suffix = identifier.rsplit("-", 1)[0]
            candidate = _canonical_token_address(suffix)
            if candidate is not None:
                return candidate
            if not _is_evm_chain(chain):
                return suffix
        if not _is_evm_chain(chain):
            return identifier
        raise ServiceError(
            code=ErrorCode.VALIDATION_ERROR,
            message="Token address is required for EVM token inspection",
            status_code=400,
            details={"identifier": identifier, "chain": chain, "token_address": token_ref.token_address},
        )

    def _resolve_chain(self, token_ref: Any) -> str:
        chain = getattr(token_ref, "chain", None)
        if chain:
            return chain
        identifier = getattr(token_ref, "identifier", "")
        if ":" in identifier:
            return identifier.split(":", 1)[0]
        if "-" in identifier:
            return identifier.rsplit("-", 1)[-1]
        return "unknown"

    def inspect_token(self, payload: InspectTokenRequest) -> dict[str, Any]:
        token_address = self._resolve_token_address(payload)
        chain = self._resolve_chain(payload.token_ref)
        token_raw = self._cli.run_json("token", "--address", token_address, "--chain", chain)
        token_data = _nested_dict(token_raw, "data", "token") or _section_dict(token_raw)
        pair_items = _section_list(token_raw, "pairs")
        risk_raw = (
            self._cli.run_json("risk", "--address", token_address, "--chain", chain)
            if payload.include_risk
            else {}
        )
        holders_raw = (
            self._cli.run_json("holders", "--address", token_address, "--chain", chain)
            if payload.include_holders
            else {}
        )
        identity = _token_reference(
            {
                **token_data,
                "identifier": _first_non_empty(token_data.get("identifier"), payload.token_ref.identifier),
                "chain": _first_non_empty(token_data.get("chain"), chain),
                "token_address": _first_non_empty(token_data.get("token_address"), token_address),
                "symbol": _first_non_empty(token_data.get("symbol"), payload.token_ref.symbol),
                "name": _first_non_empty(token_data.get("name"), payload.token_ref.name),
                "source": _first_non_empty(token_data.get("source"), "ave"),
            },
            chain=chain,
            fallback_source="ave",
        )
        market_snapshot = {
            "price_usd": _first_non_empty(token_data.get("current_price_usd"), token_data.get("price_usd"), token_data.get("price")),
            "market_cap_usd": _first_non_empty(token_data.get("market_cap_usd"), token_data.get("market_cap")),
            "fdv_usd": _first_non_empty(token_data.get("fdv_usd"), token_data.get("fdv")),
            "liquidity_usd": _first_non_empty(token_data.get("liquidity_usd"), token_data.get("tvl"), token_data.get("main_pair_tvl"), token_data.get("liquidity")),
            "volume_24h_usd": _first_non_empty(token_data.get("token_tx_volume_usd_24h"), token_data.get("volume_24h_usd"), token_data.get("volume_24h")),
            "status": "available",
            "note": _first_non_empty(token_data.get("market_note"), None),
        }
        risk_data = _section_dict(risk_raw)
        risk_flags = _as_list(_first_non_empty(risk_data.get("flags"), token_data.get("flags"), []))
        if token_data.get("is_lp_not_locked") in {"1", 1, True}:
            risk_flags.append("lp_not_locked")
        if token_data.get("has_black_method") in {"1", 1, True}:
            risk_flags.append("blacklist_capability")
        risk_snapshot = {
            "risk_level": _first_non_empty(risk_data.get("risk_level"), token_data.get("ave_risk_level"), token_data.get("risk_level")),
            "flags": risk_flags,
            "honeypot": _first_non_empty(risk_data.get("honeypot"), token_data.get("is_honeypot"), token_data.get("honeypot")),
            "buy_tax_bps": _first_non_empty(risk_data.get("buy_tax_bps"), risk_data.get("buy_tax"), token_data.get("buy_tax_bps"), token_data.get("buy_tax")),
            "sell_tax_bps": _first_non_empty(risk_data.get("sell_tax_bps"), risk_data.get("sell_tax"), token_data.get("sell_tax_bps"), token_data.get("sell_tax")),
            "status": "available" if payload.include_risk else "unavailable",
            "note": _first_non_empty(risk_data.get("note"), token_data.get("risk_note")),
        }
        holders_data = _section_dict(holders_raw)
        holder_items = _section_list(holders_raw, "holders", "items", "token_holders", "results")
        holder_snapshot = {
            "holder_count": _first_non_empty(holders_data.get("holder_count"), token_data.get("holders"), token_data.get("holder_count")),
            "top_holder_share_pct": _first_non_empty(holders_data.get("top_holder_share_pct"), token_data.get("top_holder_share_pct")),
            "holders": [
                {
                    "holder_address": _first_non_empty(item.get("holder_address"), item.get("address"), item.get("wallet_address")),
                    "quantity": _first_non_empty(item.get("quantity"), item.get("balance")),
                    "value_usd": _first_non_empty(item.get("value_usd"), item.get("usd_value")),
                    "share_pct": _first_non_empty(item.get("share_pct"), item.get("percentage")),
                    "label": _first_non_empty(item.get("label"), item.get("name")),
                }
                for item in holder_items
                if isinstance(item, dict)
            ],
            "status": "available" if payload.include_holders else "unavailable",
            "note": None if payload.include_holders else "holder data disabled by request",
        }
        main_pair_data = _best_pair_candidate(token_data, pair_items, chain=chain, fallback_token=identity)
        if main_pair_data:
            main_pair_ref = _pair_reference(main_pair_data, fallback_token=identity, fallback_chain=chain)
        else:
            main_pair_ref = {
                "identifier": f"{_first_non_empty(identity.get('symbol'), identity.get('identifier'))}/USDT",
                "chain": chain,
                "pair_address": _first_non_empty(token_data.get("main_pair_address"), token_data.get("pair_address")),
                "dex": _first_non_empty(token_data.get("dex"), token_data.get("pair_dex")),
                "base_token_ref": identity,
                "quote_token_ref": {
                    "identifier": f"{chain}:USDT" if chain else "USDT",
                    "chain": chain,
                    "token_address": None,
                    "symbol": "USDT",
                    "name": "Tether USD",
                    "source": "ave",
                },
            }
        return {
            "identity": identity,
            "market_snapshot": market_snapshot,
            "risk_snapshot": risk_snapshot,
            "holder_snapshot": holder_snapshot,
            "main_pair_ref": main_pair_ref,
            "source_meta": _source_meta(token_raw, command="token", provider=self.name),
        }

    def inspect_market(self, payload: InspectMarketRequest) -> dict[str, Any]:
        token_address = self._resolve_token_address(payload)
        chain = self._resolve_chain(payload.token_ref)
        pair_ref = payload.pair_ref
        if pair_ref is not None and pair_ref.pair_address:
            pair_address = pair_ref.pair_address
            pair_identifier = pair_ref.identifier
            selected_pair_data = _pair_reference(pair_ref.model_dump(mode="json"), fallback_token=payload.token_ref.model_dump(mode="json"), fallback_chain=chain)
        else:
            token_detail = self._cli.run_json("token", "--address", token_address, "--chain", chain)
            token_data = _nested_dict(token_detail, "data", "token") or _section_dict(token_detail)
            pair_items = _section_list(token_detail, "pairs")
            token_identity = _token_reference(
                {
                    **token_data,
                    "identifier": _first_non_empty(token_data.get("identifier"), payload.token_ref.identifier),
                    "chain": _first_non_empty(token_data.get("chain"), chain),
                    "token_address": _first_non_empty(token_data.get("token_address"), token_address),
                    "symbol": _first_non_empty(token_data.get("symbol"), payload.token_ref.symbol),
                    "name": _first_non_empty(token_data.get("name"), payload.token_ref.name),
                    "source": _first_non_empty(token_data.get("source"), "ave"),
                },
                chain=chain,
                fallback_source="ave",
            )
            pair_candidate = _best_pair_candidate(token_data, pair_items, chain=chain, fallback_token=token_identity)
            pair_ref = _pair_reference(pair_candidate, fallback_token=token_identity, fallback_chain=chain) if pair_candidate else None
            pair_address = _first_non_empty(
                _as_dict(pair_candidate).get("pair_address"),
                token_data.get("main_pair"),
                token_data.get("main_pair_address"),
                token_data.get("pair_address"),
            )
            pair_identifier = _first_non_empty(
                _as_dict(pair_candidate).get("identifier"),
                token_data.get("pair_identifier"),
                f"{_first_non_empty(token_identity.get('symbol'), token_identity.get('identifier'))}/USDT",
            )
            selected_pair_data = dict(pair_candidate or {})
        if not pair_address:
            raise ServiceError(
                code=ErrorCode.PROVIDER_ERROR,
                message="AVE token payload did not expose a usable main pair",
                status_code=502,
                details={"token_address": token_address, "chain": chain, "symbol": payload.token_ref.symbol},
            )
        pair_raw = self._cli.run_json("pair", "--address", pair_address, "--chain", chain)
        try:
            kline_raw = self._cli.run_json("kline-pair", "--address", pair_address, "--chain", chain, "--interval", "60", "--size", "24")
        except ServiceError:
            kline_raw = {}
        swaps_raw = self._cli.run_json("txs", "--address", pair_address, "--chain", chain)
        pair_data = _section_dict(pair_raw)
        kline_data = _section_dict(kline_raw)
        swap_items = _section_list(swaps_raw, "recent_swaps", "items", "txs", "swaps", "data")
        selected_pair = _pair_reference(
            {
                **selected_pair_data,
                **pair_data,
                "identifier": _first_non_empty(pair_data.get("identifier"), pair_identifier),
                "chain": _first_non_empty(pair_data.get("chain"), chain),
                "pair_address": _first_non_empty(pair_data.get("pair_address"), pair_data.get("pair"), pair_address),
                "dex": _first_non_empty(pair_data.get("dex"), pair_data.get("source")),
            },
            fallback_token=payload.token_ref.model_dump(mode="json"),
            fallback_chain=chain,
        )
        points = _section_list(kline_raw, "points", "ohlcv", "candles")
        normalized_points = _normalize_timestamp_points(points)
        recent_swaps = [
            {
                "tx_hash": _first_non_empty(item.get("tx_hash"), item.get("hash"), item.get("transaction_hash")),
                "timestamp": _first_non_empty(item.get("timestamp"), item.get("time"), utc_now()),
                "side": _first_non_empty(item.get("side"), item.get("type"), "unknown"),
                "token_ref": _token_reference(
                    _as_dict(item.get("token_ref")),
                    chain=chain,
                    fallback_source="ave",
                )
                if isinstance(item.get("token_ref"), dict)
                else None,
                "amount_base": _first_non_empty(item.get("amount_base"), item.get("base_amount")),
                "amount_quote": _first_non_empty(item.get("amount_quote"), item.get("quote_amount")),
                "trader": _first_non_empty(item.get("trader"), item.get("sender"), item.get("wallet")),
            }
            for item in swap_items
            if isinstance(item, dict)
        ]
        flow_summary = _as_dict(_first_non_empty(pair_data.get("flow_summary"), kline_data.get("flow_summary")))
        if not flow_summary:
            flow_summary = {
                "buy_count": sum(1 for item in recent_swaps if item.get("side") == "buy"),
                "sell_count": sum(1 for item in recent_swaps if item.get("side") == "sell"),
                "net_flow_usd": None,
                "large_trade_count": None,
                "note": f"{payload.window} window at {payload.interval} interval",
            }
        latest_close = None
        if normalized_points:
            latest_close = _safe_float(normalized_points[-1].get("close"))
        market_snapshot = {
            "price_usd": _first_non_empty(latest_close, pair_data.get("token1_price_usd"), pair_data.get("price_usd"), kline_data.get("price_usd"), selected_pair_data.get("price_usd")),
            "liquidity_usd": _first_non_empty(pair_data.get("liquidity_usd"), pair_data.get("tvl"), pair_data.get("liquidity"), selected_pair_data.get("liquidity_usd")),
            "volume_24h_usd": _first_non_empty(pair_data.get("volume_24h_usd"), pair_data.get("volume_u_24h"), pair_data.get("volume_24h"), selected_pair_data.get("volume_24h_usd")),
            "price_change_1h": _first_non_empty(pair_data.get("price_change_1h"), selected_pair_data.get("price_change_1h")),
            "price_change_24h": _first_non_empty(pair_data.get("price_change_24h"), pair_data.get("price_change_1d"), selected_pair_data.get("price_change_24h")),
            "status": "available",
        }
        return {
            "selected_pair": selected_pair,
            "market_snapshot": market_snapshot,
            "ohlcv": normalized_points,
            "recent_swaps": recent_swaps,
            "flow_summary": flow_summary,
            "source_meta": _source_meta(pair_raw, command="pair", provider=self.name),
        }

    def inspect_wallet(self, payload: InspectWalletRequest) -> dict[str, Any]:
        chain = payload.chain or "unknown"
        wallet_info_raw = self._cli.run_json("wallet-info", "--wallet", payload.wallet, "--chain", chain)
        wallet_tokens_raw = self._cli.run_json("wallet-tokens", "--wallet", payload.wallet, "--chain", chain)
        wallet_info = _section_dict(wallet_info_raw)
        wallet_tokens = _section_list(wallet_tokens_raw, "tokens", "items", "holdings", "rows")
        activity_pages = max(1, int(getattr(payload, "activity_pages", 1) or 1))
        recent_activity_limit = max(1, int(getattr(payload, "recent_activity_limit", 20) or 20))
        raw_activity_pages: list[dict[str, Any]] = []
        raw_activities: list[dict[str, Any]] = []
        seen_tx_hashes: set[str] = set()
        last_time: str | None = None
        last_id: str | None = None
        for page in range(1, activity_pages + 1):
            command_args = ["--wallet", payload.wallet, "--chain", chain, "--page-size", "50"]
            if last_time:
                command_args.extend(["--last-time", last_time])
            if last_id:
                command_args.extend(["--last-id", last_id])
            page_payload = self._cli.run_json("address-txs", *command_args)
            raw_activity_pages.append(page_payload)
            page_section = _section_dict(page_payload)
            page_items = _section_list(page_payload, "result", "items", "txs", "activity", "records")
            if not page_items:
                break
            new_items = 0
            for item in page_items:
                if not isinstance(item, dict):
                    continue
                tx_hash = str(
                    _first_non_empty(item.get("tx_hash"), item.get("hash"), item.get("transaction_hash"), item.get("transaction"))
                    or ""
                ).strip()
                if tx_hash and tx_hash in seen_tx_hashes:
                    continue
                if tx_hash:
                    seen_tx_hashes.add(tx_hash)
                raw_activities.append(item)
                new_items += 1
            last_time = _first_non_empty(page_section.get("last_time"), last_time)
            last_id = _first_non_empty(page_section.get("last_id"), last_id)
            if new_items == 0:
                break
        total_balance_usd = _safe_float(
            _first_non_empty(wallet_info.get("balance_usd"), wallet_info.get("total_value_usd"), wallet_info.get("total_balance"))
        )
        wallet_summary = {
            "wallet_address": _first_non_empty(wallet_info.get("wallet_address"), payload.wallet),
            "chain": _first_non_empty(wallet_info.get("chain"), chain),
            "label": _first_non_empty(wallet_info.get("label"), wallet_info.get("name")),
            "balance_usd": total_balance_usd,
            "total_balance_usd": total_balance_usd,
            "token_count": _first_non_empty(wallet_info.get("token_count"), len(wallet_tokens)),
            "status": "available",
            "note": _first_non_empty(wallet_info.get("note"), None),
            "total_profit": _first_non_empty(wallet_info.get("total_profit"), wallet_info.get("profit")),
            "total_profit_ratio": _first_non_empty(wallet_info.get("total_profit_ratio"), wallet_info.get("profit_ratio")),
            "total_win_ratio": _first_non_empty(wallet_info.get("total_win_ratio"), wallet_info.get("win_ratio")),
            "total_purchase": _first_non_empty(wallet_info.get("total_purchase"), wallet_info.get("buy_count")),
            "total_sold": _first_non_empty(wallet_info.get("total_sold"), wallet_info.get("sell_count")),
        }
        holdings = [
            _normalize_wallet_token_item(item, chain=chain, total_balance_usd=total_balance_usd)
            for item in wallet_tokens
            if isinstance(item, dict)
        ]
        full_activity_history = [
            _normalize_wallet_activity_item(item, chain=chain)
            for item in raw_activities
            if isinstance(item, dict)
        ]
        full_activity_history.sort(key=lambda item: str(item.get("timestamp") or ""), reverse=True)
        recent_activity = full_activity_history[:recent_activity_limit]
        return {
            "wallet_summary": wallet_summary,
            "holdings": holdings if payload.include_holdings else [],
            "recent_activity": recent_activity if payload.include_activity else [],
            "full_activity_history": full_activity_history if payload.include_activity else [],
            "fetch_metadata": {
                "activity_pages_fetched": len(raw_activity_pages),
                "recent_activity_limit": recent_activity_limit,
            },
            "source_meta": _source_meta(wallet_info_raw, command="wallet-info", provider=self.name),
        }

    def review_signals(self, payload: ReviewSignalsRequest) -> dict[str, Any]:
        chain = payload.chain or (payload.token_ref.chain if payload.token_ref else "solana")
        raw = self._cli.run_json("signals", "--chain", chain, "--page-size", str(payload.limit), "--page-no", "1")
        section = _section_dict(raw)
        signals = _section_list(raw, "signals", "items", "results")
        linked_refs = []
        if payload.token_ref is not None:
            linked_refs.append(_token_reference(payload.token_ref.model_dump(mode="json"), chain=chain, fallback_source="ave"))
        for item in signals:
            if isinstance(item, dict) and isinstance(item.get("token_ref"), dict):
                linked_refs.append(_token_reference(item["token_ref"], chain=chain, fallback_source="ave"))
        deduped_linked_refs: list[dict[str, Any]] = []
        seen_ids: set[str] = set()
        for token_ref in linked_refs:
            identifier = token_ref.get("identifier")
            if identifier in seen_ids:
                continue
            seen_ids.add(identifier)
            deduped_linked_refs.append(token_ref)
        normalized_signals = [
            {
                "signal_id": _first_non_empty(item.get("signal_id"), item.get("id"), item.get("title")),
                "title": _first_non_empty(item.get("title"), item.get("name"), "AVE signal"),
                "severity": _first_non_empty(item.get("severity"), "medium"),
                "chain": _first_non_empty(item.get("chain"), chain),
                "token_ref": _token_reference(item.get("token_ref"), chain=chain, fallback_source="ave")
                if isinstance(item.get("token_ref"), dict)
                else (payload.token_ref.model_dump(mode="json") if payload.token_ref else None),
                "description": _first_non_empty(item.get("description"), item.get("note")),
                "occurred_at": _first_non_empty(item.get("occurred_at"), item.get("timestamp"), utc_now()),
                "source": _first_non_empty(item.get("source"), "ave"),
            }
            for item in signals
            if isinstance(item, dict)
        ]
        return {
            "signals": normalized_signals[: payload.limit],
            "linked_token_refs": deduped_linked_refs,
            "source_meta": _source_meta(raw, command="signals", provider=self.name),
        }


def build_provider() -> ProviderAdapter:
    mode = os.environ.get("AVE_DATA_PROVIDER", "").strip().lower()
    if not mode:
        mode = "auto" if os.environ.get("AVE_API_KEY") else "mock"
    if mode in {"ave_rest", "real"}:
        script_path = Path(os.environ.get("AVE_REST_SCRIPT_PATH", DEFAULT_VENDOR_SCRIPT)).expanduser()
        python_executable = os.environ.get("AVE_REST_PYTHON", sys.executable)
        timeout_seconds = float(os.environ.get("AVE_REST_TIMEOUT_SECONDS", "30.0"))
        return AveRestProvider(script_path=script_path, python_executable=python_executable, timeout_seconds=timeout_seconds)
    if mode == "auto":
        script_path = Path(os.environ.get("AVE_REST_SCRIPT_PATH", DEFAULT_VENDOR_SCRIPT)).expanduser()
        if script_path.exists():
            python_executable = os.environ.get("AVE_REST_PYTHON", sys.executable)
            timeout_seconds = float(os.environ.get("AVE_REST_TIMEOUT_SECONDS", "30.0"))
            return AveRestProvider(script_path=script_path, python_executable=python_executable, timeout_seconds=timeout_seconds)
    return MockProvider()


def provider_error(message: str, *, status_code: int = 500, details: dict[str, Any] | None = None) -> ServiceError:
    return ServiceError(
        code=ErrorCode.PROVIDER_ERROR,
        message=message,
        status_code=status_code,
        details=details or {},
    )
